### ISSUE TITLE
bundle, libxml-ruby v2.8.0, windows error.

### ISSUE THREAD

**Issue by ghost** [shawn42/gamebox#100] opened 2016-03-04 07:08 UTC
Hello friend, I installed successfully gamebox from source, create a template but when I try to run "bundle", a bug appears with libxml-ruby 2.8.0, which apparently is a dependency of releasy . I have been researching and install the version 2.8.0 on windows is the hell, however, can easily install version 2.7.0. My question is: Is there a way to "bundle" use libxml-ruby 2.7.0 instead of version 2.8.0? 
Maybe setting it to install some older version of releasy by default. Another question: Is it possible to run a game directly by clicking on any file.rb? Without using bundle, rake, etc.

By the way, you know spanish? It's a mess for me to write in english.

**Comment by shawn42** [comment] 2016-03-04 13:12
@robinsonrisquez 
Unfortunately, I do not speak Spanish, but your English came across very well.

I believe releasy (which is a gem to help build stand-alone applications from Gosu games) has been abandoned. You can simple remove releasy from the generated Gemfile.

As for running a game from clicking a .rb file, there isn't a way to do that. You could probably modify app.rb to setup all the bundler stuff, but it doesn't right now.

Let me know if you have further questions.

**Comment by robinsonrisquez** [comment] 2016-03-05 20:49
Thanks for answering. Yes, I tried to remove releasy of Gemfile but when I do 'rake', this tells me that the releasy dependency is missing. The Rakefile performs various operations with releasy. Maybe libxml-ruby soon launch a compiled gem for windows as he had done with previous versions.

There is an issue in the repository of releasy where ask for this error and the author says that the problem is in libxml-ruby 2.8.0 and escapes from his hands.

https://github.com/Spooner/releasy/issues/63

**Comment by shawn42** [comment] 2016-03-06 15:30
You are correct.  

You'll need to comment out the releasy stuff in the Rakefile (first occurrence of Releasy on down) and comment out `require 'releasy'` from the config/environment.rb file. After that, `bundle exec rake run` should work fine.  I should probably make releasy entirely optional and check if it's installed. I'll keep this issue open until I do.

Thanks again.

**Comment by robinsonrisquez** [comment] 2016-03-07 08:05
With this solution now bundler and rake work perfectly!, the game runs smoothly.

I was doing some tests and noticed that releasy is installed perfectly if before you install the latest compiled version for windows of libxml (`gem install libxml-ruby -v 2.7.0`), but when you 'bundle' inevitably it try to upgrade to 2.8.0; and as releasy depends on bundler... the error occurs (At least in windows).

Now would be to seek a way to create an executable. I tested directly ocra with `src/app.rb` but...

**Comment by shawn42** [comment] 2016-03-10 16:55
You should still be able to package everything up with ocra. If you post specific problems, I'll try to help.

**Comment by shawn42** [comment] 2017-03-30 06:36
Closing because of no new data.

**Closed** 2017-03-30 06:36 UTC
